// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const url =
  process.env['NODE_ENV'] === 'test' ?
    process.env['DATABASE_URL_TEST']
  : process.env['DATABASE_URL'];

if (!url) {
  console.error('DATABASE_URL is not defined in environment variables');
  console.table(process.env);
  throw new Error('DATABASE_URL is not defined in environment variables');
}

export default defineConfig({
  schema: 'prisma/',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url,
  },
});
